MenuScreen:


<MenuScreen>:
    on_pre_enter: root.reset_game_won()
    Button:
        text: "FIGHT ! "
        on_press: root.manager.current = 'combat'


<FightScreen>:
    MainWidget:

<GameOverScreen>:
    on_pre_enter: root.game_over_sound.play(), root.reset_game_over()
    on_leave: root.game_over_sound.stop()
    RelativeLayout:
        Label:
            text: "GAME OVER"
            color: 1, 0, 0
            font_size: dp(100)
            font_name: "fonts/Dragon_Fire.otf"
        Button:
            size_hint: 0.2, 0.1
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            text: "TRY AGAIN"
            on_release: root.manager.current = 'menu'

<MainWidget>:
    BoxLayout:
        orientation : "vertical"
        BoxLayout:
            size_hint: 1, 0.1
            ProgressBar:
                value: root.hero_xp
        RelativeLayout:
            Image:
                id: Ennemy_img
                source: root.Ennemy_img
            Image:
                id: Effect_spell
                source: root.Effect_img
        ProgressBar:
            size_hint: (root.monster_hp - root.monster_hp_lost) / root.monster_hp, 0.1
            canvas:
                BorderImage:
                    border: (12, 12, 12, 12)
                    pos: self.x, self.center_y - 12
                    size: self.width, 24
                    source: 'images/red.png'
        BoxLayout:
            orientation: "horizontal"
            RelativeLayout:
                MenuFull:
                    id: menu_full
                Button:
                    size_hint: root.ennemy_turn, root.ennemy_turn
                    text: "ENNEMY TURN"
                    size: 0, 0
                    opacity: 0
                    disabled: True
            PlayerInfo:
                orientation : "horizontal"
                RelativeLayout:
                    Image:
                        source : 'images/mage.png'
                    Image:
                        source : root.monster_attack_effect
                BoxLayout:
                    orientation: "vertical"
                    Label :
                        text : "NAME"
                    Label :
                        text : "HP : "
                    ProgressBar:
                        size_hint: (root.hero_hp - root.hero_hp_lost) / root.hero_hp, 0.1
                        canvas:
                            BorderImage:
                                border: (12, 12, 12, 12)
                                pos: self.x, self.center_y - 12
                                size: self.width, 24
                                source: 'images/red.png'
                    Label :
                        text : " MP : "
                    ProgressBar:
                        size_hint: (root.hero_mp - root.hero_mp_lost) / root.hero_mp, 0.1
                        canvas:
                            BorderImage:
                                border: (12, 12, 12, 12)
                                pos: self.x, self.center_y - 12
                                size: self.width, 24
                                source: 'images/blue.png'
                    Label :
                        text : "LVL : " + str(root.hero_lvl)



<MenuFull>:
    do_default_tab: False
    TabbedPanelItem:
        text: "Attaque"
        Button:
            text: "Attack"
            disabled: True if root.ennemy_turn == True else False
            on_press: root.ennemy_turn_on(), self.parent.parent.parent.parent.parent.parent.on_attack(), self.parent.parent.parent.parent.parent.parent.parent.check_game_end()
    TabbedPanelItem
        text: "Magic"
        MagicMenu:
    TabbedPanelItem
        text: "Objets"
        ObjectMenu:
            id: object_menu
    TabbedPanelItem
        text: "Fuite"
        MagicMenu:


<MagicMenu>:
    orientation : "vertical"
    Button:
        text: "Fireball"
        on_press: self.parent.parent.parent.parent.parent.parent.parent.on_spell_fire_pressed(), self.parent.parent.parent.parent.parent.parent.parent.parent.check_game_end()
    Button:
        text: "Healing"
        on_press: self.parent.parent.parent.parent.parent.parent.parent.on_spell_heal_pressed(), self.parent.parent.parent.parent.parent.parent.parent.parent.check_game_end()
    Button:
        text: "tornado"
        on_press: self.parent.parent.parent.parent.parent.parent.parent.on_spell_wind_pressed(), self.parent.parent.parent.parent.parent.parent.parent.parent.check_game_end()


<ObjectMenu>:
    orientation : "vertical"
    BoxLayout:
        Button:
            text: "Healing Potion"
            on_press: self.parent.parent.parent.parent.parent.parent.parent.parent.on_object_1_pressed(), self.parent.parent.parent.parent.parent.parent.parent.parent.parent.check_game_end(), root.on_object_1_pressed()
        Button:
            disabled: True
            disabled_color: 1, 1, 1, 1
            size_hint: 0.2, 1
            text: "x" + str(root.object_1_qty)
    BoxLayout:
        Button:
            text: "Mana Potion"
            on_press: self.parent.parent.parent.parent.parent.parent.parent.parent.on_object_2_pressed(), self.parent.parent.parent.parent.parent.parent.parent.parent.parent.check_game_end(), root.on_object_2_pressed()
        Button:
            disabled: True
            disabled_color: 1, 1, 1, 1
            size_hint: 0.2, 1
            text: "x" + str(root.object_2_qty)
    BoxLayout:
        Button:
            text: "Explosive Potion"
            on_press: self.parent.parent.parent.parent.parent.parent.parent.parent.on_object_3_pressed(), self.parent.parent.parent.parent.parent.parent.parent.parent.parent.check_game_end(), root.on_object_3_pressed()
        Button:
            id : object_3
            disabled: True
            disabled_color: 1, 1, 1, 1
            size_hint: 0.2, 1
            text: "x" + str(root.object_3_qty)