MainWidget:

<MainWidget>:
    orientation : "vertical"
    Label:
        size_hint: 1, None
        size: 200, 200
        pos: 200, 200
        canvas:
            Color:
                rgba: 1, 0, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
    BoxLayout:
        orientation : "vertical"
        AttacksButton:
        MagicButton:
        ObjectButton:
        FleeButton: